version: "3.8"

services:
  eve_mock:
    build: .
    # keep hostname set to `slurmctl`.  See README in
    # base image why this is needed.
    # this image:  giovtorres/docker-centos7-slurm:21.08.0
    # development: https://github.com/giovtorres/docker-centos7-slurm
    hostname: slurmctl
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 5
    volumes:
      - ./work:/work
      - ./src:/home/sontsm
